resumemake/account/views.py
from flask import render_template, request, Blueprint, redirect, url_for, flash, abort
from werkzeug.security import generate_password_hash, check_password_hash
from resumemake.models import Users
from datetime import datetime
from resumemake import db, login_manager
from flask_login import login_user, logout_user, login_required, current_user
from utils import only_main

account = Blueprint('account',__name__)

@login_manager.user_loader
def load_user(id):
    return Users.query.get(int(id))

@account.route('/login', methods=['GET', 'POST'])
@only_main()
def login():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard.mysites'))
    if request.method == 'POST':
        login_eu = request.form['login-eu']
        password = request.form['login-password']

        if "@" in login_eu:
            user = Users.query.filter_by(email=login_eu).first()
        else:
            user = Users.query.filter_by(username=login_eu).first()

        if user:
            if check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('dashboard.mysites'))
            else:
                flash('Wrong Credentials!')
                return render_template('account/login.html')
        else:
            flash('User not found!')
            return render_template('account/login.html')
    return render_template('account/login.html')

@account.route('/signup', methods=['GET','POST'])
@only_main()
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('public.index'))
    if request.method == 'POST':
        username = request.form['register-username']
        email = request.form['register-email']
        password = request.form['register-password']
        confirm = request.form['confirm-password']
        if password != confirm:
            flash('Passwords not matched! Try again')
            return render_template('account/register.html')
        if not username.isalnum():
            flash('username should be alpha numeric!')
            return render_template('account/register.html')
        hashed_password = generate_password_hash(password, method='sha256')
        existing_username = Users.query.filter_by(username=username).first()
        if existing_username is not None:
            flash('Username already being used!')
            return render_template('account/register.html')
        else:
            existing_email = Users.query.filter_by(email=email).first()
            if existing_email is not None:
                flash('Email already being used')
                return render_template('account/register.html')
            else:
                new_user = Users(username=username, email=email, password=hashed_password)
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
                return redirect(url_for('dashboard.mysites'))
    return render_template('account/register.html')

@account.route('/logout')
@login_required
@only_main()
def logout():
    logout_user()
    return redirect(url_for('public.index'))

resumemake/dashboard/views.py
from flask import render_template, Blueprint, request, jsonify, redirect, url_for
from flask_login import current_user, login_required
from utils import RESUME_SITES_NAMES
from resumemake import db
from resumemake.models import ResumeSite
import uuid

dashboard = Blueprint('dashboard',__name__)

@dashboard.route('/templates')
@login_required
def templates():
    return render_template('dashboard/create-site.html')

@dashboard.route('/my-sites')
@login_required
def mysites():
    return render_template('dashboard/my-sites.html')

@dashboard.route('/delete-site/<sitetype>/<site_id>')
@login_required
def deletesite(sitetype, site_id):
    if sitetype == 'resume':
        site = ResumeSite.query.filter_by(site_id=site_id, owner=current_user).first()
    if site:
        db.session.delete(site)
        db.session.commit()
        return jsonify({'success': True})
    else:
        return jsonify({'success': False})

@dashboard.route('/create-site', methods=['POST'])
@login_required
def createsite():
    site_name = request.form['site_name']
    template = request.form['template']
    if len(site_name.strip()) < 3 or len(site_name.strip()) > 30:
        return jsonify({'success': False, "msg": "Site name should be between 3 and 30 characters!"})
    else:
        if template in RESUME_SITES_NAMES:
            if ResumeSite.query.filter_by(site_name=site_name, owner=current_user).first():
                return jsonify({'success': False, "msg": "This site of yours already exist!"})
            else:
                site_id = str(uuid.uuid4())
                new_site = ResumeSite(site_id=site_id, site_name=site_name, template=template, user_id=current_user.id)
                db.session.add(new_site)
                db.session.commit()
                return jsonify({'success': True, "msg": url_for('resume.resumecreate', site_id=site_id, site_name=site_name)})
        else:
            return jsonify({'success': False, "msg": "Something went wrong! Refresh the page please."})

@dashboard.route('/thanks')
@login_required
def thanks():
    return render_template('pricing/thanks.html')

@dashboard.route('/publish/<site_id>')
@login_required
def publish(site_id):
    site = ResumeSite.query.filter_by(site_id=site_id).first()
    site.current_plan = 'published'
    db.session.commit()
    return redirect(url_for('.thanks'))

resumemake/messages/views.py
from flask import render_template, Blueprint, jsonify
from flask_login import login_required, current_user
from resumemake.models import UserMails, Notifications
from resumemake import db

messages = Blueprint('messages',__name__)

@messages.route('/inbox')
@login_required
def inbox():
    notifs = Notifications.query.all()
    for notif in notifs:
        db.session.delete(notif)
    db.session.commit()
    return render_template('messages/inbox.html')

@messages.route('/get-message/<int:mail_id>')
@login_required
def getMessage(mail_id):
    data = UserMails.query.filter_by(id=mail_id).first()
    if not data:
        return jsonify({"msg": "Something went wrong! Refresh the page."})
    if current_user == data.mailed:
        return jsonify({"success": True, "content": data.content, "subject": data.subject})
    else:
        return jsonify({"msg": "You do not have a permission!"})

@messages.route('/delete-message/<int:mail_id>')
@login_required
def deleteMessage(mail_id):
    mail = UserMails.query.filter_by(id=mail_id, mailed=current_user).first()
    if not mail:
        return jsonify({"success": False, "msg": "Something went wrong! Refresh the page."})

    db.session.delete(mail)
    db.session.commit()

    return jsonify({"success": True})

resumemake/settings/views.py
from flask import render_template, Blueprint, request, jsonify
from flask_login import login_required, current_user
from utils import allowed_img_file, get_extension, UPLOAD_PROFILE_FOLDER
from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash, check_password_hash
from resumemake import db
import os, uuid

settings = Blueprint('settings',__name__)

@settings.route('/settings', methods=['GET'])
@login_required
def setting():
    return render_template('settings/settings.html')

@settings.route('/accountGeneral', methods=['POST'])
@login_required
def accountGeneral():
    current_user.name = request.form['name']
    current_user.surname = request.form['surname']
    current_user.email = request.form['email']
    current_user.username = request.form['username']
    current_user.account_desc = request.form['account_desc']

    if 'file' in request.files:
        file = request.files['file']
        filename = file.filename
        if allowed_img_file(filename):
            filename = secure_filename(filename)
            unique_filename = str(uuid.uuid4())+get_extension(filename)
            current_user.profile_picture = unique_filename
            file.save(os.path.join(UPLOAD_PROFILE_FOLDER, unique_filename))

    db.session.commit()

    context = {
        "success": True, 
        "current_field": "acc_g", 
    }
    return jsonify(context)

@settings.route('/changePass', methods=['POST'])
@login_required
def changePass():
    old_pass = request.form['old_pass']
    new_pass = request.form['new_pass']
    retype_pass = request.form['retype_pass']

    if len(new_pass.strip()) < 6 or new_pass != retype_pass or not check_password_hash(current_user.password, old_pass):
        return jsonify({"success": False, "msg": "Some thing went wrong. Reason might be your password length is less than 6, or passwords didn't match or your password is not on our systems!"})
    else:
        current_user.password = generate_password_hash(new_pass, method='sha256')
        db.session.commit()
        return jsonify({"success": True, "current_field": "cp", "msg": "Your password has been changed!"})

resumemake/templates/_index-header.html
<!-- Navbar STart -->
<header id="topnav" class="defaultscroll sticky">
    <div class="container">
        <!-- Logo container-->
        <a class="logo" href="{{ url_for('public.index') }}">
          <img src="{{ url_for('static', filename='images/logo.png')}}" alt="missing_logo" height="36" style="margin-right: 5px;">
          <img src="{{ url_for('static', filename='images/webpaget.png')}}" style="color: blue;margin-top: 25px; float: right;">
        </a>
        <div class="buy-button">
            <a href="{{ url_for('account.signup') }}" class="btn btn-primary">Sign Up</a>
        </div><!--end login button-->
        <!-- End Logo container-->
        <div class="menu-extras">
            <div class="menu-item">
                <!-- Mobile menu toggle-->
                <a class="navbar-toggle" id="isToggle" onclick="toggleMenu()">
                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </a>
                <!-- End mobile menu toggle-->
            </div>
        </div>

        <div id="navigation">
            <!-- Navigation Menu-->
            <ul class="navigation-menu">
                <li class="has-submenu parent-parent-menu-item">
                    <a href="#templates">Templates</a>
                </li>

                <li class="has-submenu parent-parent-menu-item">
                    <a href="#faq">Faq</a>

                </li>
                <li class="has-submenu parent-menu-item">
                    <a href="#contact">Contact</a>
                </li>
            </ul><!--end navigation menu-->
            <div class="buy-menu-btn d-none">
                <a href="{{ url_for('account.signup') }}" class="btn btn-primary">Sign Up</a>
            </div><!--end login button-->
        </div><!--end navigation-->
    </div><!--end container-->
</header><!--end header-->
<!-- Navbar End -->

resumemake/templates/_menu.html
<!-- BEGIN: Main Menu-->
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
  <div class="navbar-header">
    <ul class="nav navbar-nav flex-row">
      <li class="nav-item mr-auto"><a class="navbar-brand" href="html/ltr/vertical-menu-template/index.html"><span class="brand-logo">
            <img src="{{ url_for('static', filename='images/logo.png')}}" alt="missing_logo" height="36"></span>
          <h2 class="brand-text" style="font-size: medium; margin-left: -10px;">Webpaget</h2></a></li>
      <li class="nav-item nav-toggle" style="margin-top: 5px;"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i class="d-block d-xl-none text-primary toggle-icon font-medium-4" data-feather="x"></i><i class="d-none d-xl-block collapse-toggle-icon font-medium-4  text-primary" data-feather="disc" data-ticon="disc"></i></a></li>
    </ul>
  </div>
  <div class="shadow-bottom"></div>
  <div class="main-menu-content">
    <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">

      <li class=" navigation-header"><span>Apps &amp; Menu</span><i data-feather="more-horizontal"></i>
      </li>
      <li class=" nav-item"><a class="d-flex align-items-center" href="{{ url_for('dashboard.mysites')}}"><i data-feather="globe"></i><span class="menu-title text-truncate" data-i18n="Email">My sites</span></a>
      </li>
      <li class=" nav-item"><a class="d-flex align-items-center" href="{{ url_for('messages.inbox')}}"><i data-feather="mail"></i><span class="menu-title text-truncate" data-i18n="Email">Messages</span></a>
      </li>
      <li class=" nav-item"><a class="d-flex align-items-center" href="{{ url_for('dashboard.templates') }}"><i data-feather="file"></i><span class="menu-title text-truncate" data-i18n="File Manager">Create Site</span></a>
      </li>
      <li class=" nav-item"><a class="d-flex align-items-center" href="{{ url_for('settings.setting')}}"><i data-feather="settings"></i><span class="menu-title text-truncate" data-i18n="Typography">Settings</span></a>
      </li>
  </div>
</div>
<!-- END: Main Menu-->

resumemake/templates/nav_dash.html
<!-- BEGIN: Header-->
<nav class="header-navbar navbar navbar-expand-lg align-items-center navbar-light navbar-shadow bg-dark navbar-dark fixed-top">
  <div class="navbar-container d-flex content">
    <ul class="nav navbar-nav align-items-center ml-auto">
      <li class="nav-item dropdown dropdown-notification mr-25">
        <a class="nav-link" href="javascript:void(0);" data-toggle="dropdown">
          <i class="ficon" data-feather="bell"></i>
        <span class="badge badge-pill badge-danger badge-up" id="badge_bell">{{ current_user.num_not() }}</span>
      </a>
        <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
          <li class="dropdown-menu-header">
            <div class="dropdown-header d-flex">
              <h4 class="notification-title mb-0 mr-auto">Notifications</h4>
              <div class="badge badge-pill badge-light-primary">{{ current_user.num_not() }} New</div>
            </div>
          </li>
          <li class="scrollable-container media-list">
            {% for nt in current_user.new_notifications() %}
              {% if nt.not_type == 1 %}
                <a class="d-flex" href="{{ url_for('messages.inbox') }}">
                  <div class="media d-flex align-items-start">
                    <div class="media-left">
                      <div class="avatar"><img src="{{ url_for('static', filename='images/profiles/guest.jfif')}}" alt="avatar" width="32" height="32"></div>
                    </div>
                    <div class="media-body">
                      <p class="media-heading"><span class="font-weight-bolder">You have {{ current_user.num_not() }} unseen messages</p><small class="notification-text"> someone send you a message.</small>
                    </div>
                  </div>
                </a>
              {% endif %}
            {% endfor %}
          </li>
          <li class="dropdown-menu-footer"><a class="btn btn-primary btn-block" href="{{ url_for('messages.inbox') }}">Read all notifications</a></li>
        </ul>
      </li>
      <li class="nav-item dropdown dropdown-user"><a class="nav-link dropdown-toggle dropdown-user-link" id="dropdown-user" href="javascript:void(0);" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="user-nav d-sm-flex d-none"><span class="user-name font-weight-bolder">{{ current_user }}</span><span class="user-status">Admin</span></div><span class="avatar"><img class="round" src="{{ url_for('static', filename='images/profiles/'+current_user.profile_picture) }}" alt="avatar" height="40" width="40"><span class="avatar-status-online"></span></span></a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-user">
          <a class="dropdown-item" href="{{ url_for('messages.inbox') }}"><i class="mr-50" data-feather="mail"></i> Inbox</a>
          <a class="dropdown-item" href="{{ url_for('dashboard.mysites') }}"><i class="mr-50" data-feather="bell"></i> My Sites</a>
          <a class="dropdown-item" href="{{ url_for('settings.setting') }}"><i class="mr-50" data-feather="settings"></i> Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ url_for('account.logout') }}"><i class="mr-50" data-feather="power"></i> Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!-- END: Header-->

<script>
  var badge = document.getElementById('badge_bell');
  if (parseInt(badge.innerText) == 0){
    badge.style.visibility = 'hidden';
  }
  else{
    badge.style.visibility = 'visible';
  }
</script>