resumemake/dashboard/views.py
from flask import render_template, Blueprint, request, jsonify, redirect, url_for
from flask_login import current_user, login_required
from utils import RESUME_SITES_NAMES
from resumemake import db
from resumemake.models import ResumeSite
import uuid

dashboard = Blueprint('dashboard',__name__)

@dashboard.route('/templates')
@login_required
def templates():
    return render_template('dashboard/create-site.html')

@dashboard.route('/my-sites')
@login_required
def mysites():
    return render_template('dashboard/my-sites.html')

@dashboard.route('/delete-site/<sitetype>/<site_id>')
@login_required
def deletesite(sitetype, site_id):
    if sitetype == 'resume':
        site = ResumeSite.query.filter_by(site_id=site_id, owner=current_user).first()
    if site:
        db.session.delete(site)
        db.session.commit()
        return jsonify({'success': True})
    else:
        return jsonify({'success': False})

@dashboard.route('/create-site', methods=['POST'])
@login_required
def createsite():
    site_name = request.form['site_name']
    template = request.form['template']
    if len(site_name.strip()) < 3 or len(site_name.strip()) > 30:
        return jsonify({'success': False, "msg": "Site name should be between 3 and 30 characters!"})
    else:
        if template in RESUME_SITES_NAMES:
            if ResumeSite.query.filter_by(site_name=site_name, owner=current_user).first():
                return jsonify({'success': False, "msg": "This site of yours already exist!"})
            else:
                site_id = str(uuid.uuid4())
                new_site = ResumeSite(site_id=site_id, site_name=site_name, template=template, user_id=current_user.id)
                db.session.add(new_site)
                db.session.commit()
                return jsonify({'success': True, "msg": url_for('resume.resumecreate', site_id=site_id, site_name=site_name)})
        else:
            return jsonify({'success': False, "msg": "Something went wrong! Refresh the page please."})

@dashboard.route('/thanks')
@login_required
def thanks():
    return render_template('pricing/thanks.html')

@dashboard.route('/publish/<site_id>')
@login_required
def publish(site_id):
    site = ResumeSite.query.filter_by(site_id=site_id).first()
    site.current_plan = 'published'
    db.session.commit()
    return redirect(url_for('.thanks'))

resumemake/templates/pricing/pricing.html
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
  <!-- BEGIN: Head-->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>Pricing</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">
    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/vendors.min.css')}}">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/bootstrap-extended.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/colors.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/components.min.css')}}">

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/core/menu/menu-types/vertical-menu.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/pages/page-pricing.min.css')}}">

    <!-- END: Page CSS-->
  </head>
  <!-- END: Head-->

  <!-- BEGIN: Body-->
  <body class="vertical-layout footer-static pace-done menu-hide vertical-overlay-menu navbar-sticky menu-collapsed" data-open="click" data-menu="vertical-menu-modern" data-col="">

    {% include 'nav_dash.html' %}

    {% include '_menu.html' %}

    <div class="app-content content ">
      <div class="content-overlay"></div>
      <div class="header-navbar-shadow"></div>
      <div class="content-wrapper container-xxl p-0">
        <div class="content-header row">
        </div>
        <div class="content-body">
          <section id="pricing-plan">

            <div class="row pricing-card">
              <div class="col-12 col-sm-offset-2 col-sm-10 col-md-12 col-lg-offset-2 col-lg-10 mx-auto">
                <div class="row justify-content-center align-items-center">
                  
                  <!-- only plan -->
                  <div class="col-12 col-md-6">
                    <div class="card standard-pricing popular text-center">
                      <div class="card-body">
                        <div class="pricing-badge text-end">
                          <span class="badge rounded-pill badge-light-primary">Popular</span>
                        </div>
                        <img src="{{ url_for('static', filename='images/Pot2.svg')}}" class="mb-1" alt="svg img">
                        <h3>Standard</h3>
                        <p class="card-text">For small to medium businesses</p>
                        <div class="annual-plan">
                          <div class="plan-price mt-2">
                            <sup class="font-medium-1 fw-bold text-primary">$</sup>
                            <span class="pricing-standard-value fw-bolder text-primary">49</span>
                            <sub class="pricing-duration text-body font-medium-1 fw-bold">/month</sub>
                          </div>
                          <small class="annual-pricing d-none text-muted"></small>
                        </div>
                        <ul class="list-group list-group-circle text-center " style="display: inline-block;">
                          <li class="list-group-item">Unlimited responses</li>
                          <li class="list-group-item">Unlimited forms and surveys</li>
                          <li class="list-group-item">Instagram profile page</li>
                          <li class="list-group-item">Google Docs integration</li>
                          <li class="list-group-item">Custom “Thank you” page</li>
                        </ul>
                        <button class="btn w-100 btn-primary mt-2 waves-effect waves-float waves-light" id="buy">Upgrade</button>
                      </div>
                    </div>
                  </div>
                  <!--/ only plan -->
                  
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <button class="btn btn-primary btn-icon scroll-top" type="button"><i data-feather="arrow-up"></i></button>
    <!-- END: Footer-->

    <!-- BEGIN: Vendor JS-->
    <script src="{{ url_for('static', filename='assets/js/vendors.min.js')}}"></script>

    <!-- BEGIN: Theme JS-->
    <script src="{{ url_for('static', filename='assets/js/core/app-menu.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/js/core/app.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/js/scripts/customizer.min.js')}}"></script>
		<script src="https://cdn.paddle.com/paddle/paddle.js"></script>

		<script type="text/javascript">
		  Paddle.Environment.set('sandbox');
		  Paddle.Setup({ vendor: 2061 });

			function openCheckout() {
				Paddle.Checkout.open({
					product: 15888,
					email: '{{ current_user.email }}',
					allowQuantity: false,
					success: '{{ url_for("dashboard.publish", site_id="kkvkkv") }}'
				});
			}
			document.getElementById('buy').addEventListener('click', openCheckout, false);

		</script>

    <script>
      $(window).on('load',  function(){
        if (feather) {
          feather.replace({ width: 14, height: 14 });
        }
      })
    </script>

  </body>
  <!-- END: Body-->
</html>

resumemake/templates/pricing/thanks.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Thank you for the purchase</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/bootstrap-extended.min.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700" rel="stylesheet" media="screen">
    <style>
      .hover-underline:hover {
        text-decoration: underline !important;
      }

      @keyframes spin {
        to {
          transform: rotate(360deg);
        }
      }

      @keyframes ping {

        75%,
        100% {
          transform: scale(2);
          opacity: 0;
        }
      }

      @keyframes pulse {
        50% {
          opacity: .5;
        }
      }

      @keyframes bounce {

        0%,
        100% {
          transform: translateY(-25%);
          animation-timing-function: cubic-bezier(0.8, 0, 1, 1);
        }

        50% {
          transform: none;
          animation-timing-function: cubic-bezier(0, 0, 0.2, 1);
        }
      }

      @media (max-width: 600px) {
        .sm-leading-32 {
          line-height: 32px !important;
        }

        .sm-px-24 {
          padding-left: 24px !important;
          padding-right: 24px !important;
        }

        .sm-py-32 {
          padding-top: 32px !important;
          padding-bottom: 32px !important;
        }

        .sm-w-full {
          width: 100% !important;
        }
      }
    </style>
  </head>

  <body style="margin: 0; padding: 0; width: 100%; word-break: break-word; -webkit-font-smoothing: antialiased; --bg-opacity: 1; background-color: #eceff1; background-color: rgba(236, 239, 241, var(--bg-opacity));">
    <div role="article" aria-roledescription="email" aria-label="Welcome 👋" lang="en">
      <table style="font-family: Montserrat, -apple-system, 'Segoe UI', sans-serif; width: 100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation">
        <tr>
          <td align="center" style="--bg-opacity: 1; background-color: #eceff1; background-color: rgba(236, 239, 241, var(--bg-opacity)); font-family: Montserrat, -apple-system, 'Segoe UI', sans-serif;" bgcolor="rgba(236, 239, 241, var(--bg-opacity))">
            <table class="sm-w-full" style="font-family: 'Montserrat',Arial,sans-serif; width: 600px;" width="600" cellpadding="0" cellspacing="0" role="presentation">
              <tr>
                <td class="sm-py-32 sm-px-24" style="font-family: Montserrat, -apple-system, 'Segoe UI', sans-serif; padding: 20px; text-align: center;" align="center">
                </td>
              </tr>
              <tr>
                <td align="center" class="sm-px-24" style="font-family: 'Montserrat',Arial,sans-serif;">
                  <table style="font-family: 'Montserrat',Arial,sans-serif; width: 100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation">
                    <tr>
                      <td class="sm-px-24" style="--bg-opacity: 1; background-color: #ffffff; background-color: rgba(255, 255, 255, var(--bg-opacity)); border-radius: 4px; font-family: Montserrat, -apple-system, 'Segoe UI', sans-serif; font-size: 14px; line-height: 24px; padding: 48px; text-align: left; --text-opacity: 1; color: #626262; color: rgba(98, 98, 98, var(--text-opacity));" bgcolor="rgba(255, 255, 255, var(--bg-opacity))" align="left">
                        <p></p>
                        <p class="sm-leading-32" style="font-weight: 600; font-size: 30px; margin: 0 0 24px; --text-opacity: 1; color: #263238; color: rgba(38, 50, 56, var(--text-opacity));">
                          Thank you for your purchase
                        <p>
                           Your order has been received. Connect your domain if you didn't do. This may take up to 24 hours to take effect.
                        </p>
                        <p style="margin: 24px 0;">
                          You can now return to your sites page.
                        </p>
                          <table style="font-family: 'Montserrat',Arial,sans-serif;" cellpadding="0" cellspacing="0" role="presentation">
                            <tr>
                              <td style="mso-padding-alt: 16px 24px; --bg-opacity: 1; background-color: #7367f0; background-color: rgba(115, 103, 240, var(--bg-opacity)); border-radius: 4px; font-family: Montserrat, -apple-system, 'Segoe UI', sans-serif;" bgcolor="rgba(115, 103, 240, var(--bg-opacity))">
                                <a href="{{ url_for('dashboard.mysites') }}" style="display: block; font-weight: 600; font-size: 14px; line-height: 100%; padding: 16px 24px; --text-opacity: 1; color: #ffffff; color: rgba(255, 255, 255, var(--text-opacity)); text-decoration: none;">Go to your sites</a>
                              </td>
                            </tr>
                          </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </div>
  </body>

</html>